name: Ensure SyncR.Server Builds

on:
  pull_request:
    branches:
      - main
    paths:
      - src/SyncR.Server/*
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/SyncR.Server/
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build -c Release